#!/bin/bash

shopt -s checkwinsize

# Prompt
if [ -n "$PS1" ]; then # prevent WinSCP issues
	if [ "$(tput colors)" -gt 0 ] ; then
		RED=$(tput setaf 1)
		GREEN=$(tput setaf 2)
		CYAN=$(tput setaf 6)
		RESET=$(tput sgr0)
	fi
	bash_prompt_command() {
		RTN=$?
		# OK
		if [ $RTN == 0 ]; then
			RES=$GREEN

		# EXCEPTIONS
		elif [ $RTN == 130 ]; then # CTRL+C
			RES=$GREEN
		elif [ $RTN == 147 ]; then # BREAK (ls command)
			RES=$GREEN
		elif [ $RTN == 148 ]; then # BREAK (vim)
			RES=$GREEN
#		elif [ $RTN == 127 ]; then # 'command not found'
#			RES=$GREEN

		# ERROR
		else
			RES=$RED
		fi
		history -a
	}
	PROMPT_COMMAND=bash_prompt_command
	PS1='\[$RESET\]\[$CYAN\]\h\[$GREEN\]:\w\[$RES\]\$\[$RESET\] '
fi
