#!/bin/bash

set -ue

UPDATE_LOG=/tmp/apt.update

# Run 'apt update' and fail if output contains a line starting with "err"
exe2 --title "Checking for updates" "set -e; apt -q update 2>/dev/null | tee '$UPDATE_LOG'; if grep -qi ^err '$UPDATE_LOG'; then false; else true; fi"

if ! grep -qF "All packages are up to date" "$UPDATE_LOG"; then
	echo
	apt list --upgradable
fi

echo
