#!/bin/bash

[ -z "$1" ] && {
	echo -e "Search file by case insensitive partial <filename>.\n" >&2
	echo -e "Syntax: ${0##*/} <filename> [<additional find options>]\n" >&2
	exit 1
}

NEEDLE="$1"
shift

find . -iname "*$NEEDLE*" "$@"
