#!/bin/bash

[ -z "$1" ] && {
	echo -e "Search file by case insensitive partial <filename>.\n"
	echo -e "Syntax: ${0##*/} <filename> [<additional find options>]\n"
	exit 1
} >&2

NEEDLE="$1"
shift

find . -iname "*$NEEDLE*" "$@"
