#!/bin/bash

set -ueo pipefail

if [ -z "${TRASHDIR:-}" ]; then
	echo 'Error: $TRASHDIR is not set.'
	echo
	exit 1
fi >&2

checkBinarys() {
	for i in "$@"; do
		hash "$i" 2>/dev/null || {
			echo "Error: Binary '$i' is missing."
			echo
			exit 1
		} >&2
	done
}

BINS=("rm")
[ $# -gt 0 ] && BINS+=("find" "shred")
checkBinarys "${BINS[@]}"

# shred files?
if [ $# -eq 1 ] && [ "$1" == '--shred' ]; then
	# shred all files, skip if link count is > 1
	find "$TRASHDIR" -type f -links 1 -exec shred -vn 1 "{}" \;
elif [ $# -gt 0 ]; then
	# get file extensions from command line arguments
	# shred files matching extension, skip if link count is > 1
	for i in "$@"; do
		find "$TRASHDIR" -type f -links 1 -iname "*.$i" -exec shred -vn 1 "{}" \;
	done
fi

echo "Deleting files.."
rm -rf "$TRASHDIR"
echo
